### ISSUE TITLE
Return empty set, not None when no match is found

### ISSUE THREAD

**Issue by NickCrews** [constituentvoice/PyNameMatcher#1]
Not sure if this is maintained at all, but I'd submit a PR if so.

It's annoying how the return type of match() is normally a set, but changes to None when there is no match. Returning an empty set would allow for much for idiomatic code like `for m in my_matcher.match("name"):`

Thanks!

**Comment by cfreak-dev** [comment]
Hi Nick! Yes, we still use this. It's been working so we haven't had an occasion to update the project. I'd be happy to take a look at a PR if you want to submit one.

**Comment by NickCrews** [comment]
Thanks for the quick reply @chrisbrownnwyc ! There's my PR, take a look

**Comment by cfreak-dev** [comment]
@NickCrews I've added tests and a flag that restores the old behavior. The new version is up on pypi.
